name: COMP579_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.7.0=py37h8f50634_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - blosc=1.21.0=h8c45485_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h5e8e339_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.2.1=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2021.10.8=py37h06a4308_2
  - cfitsio=3.470=hf0d0db6_6
  - chardet=3.0.4=py37he5f6b98_1008
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.4=py37h89c1867_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cryptography=36.0.1=py37hf1a17b8_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py37h7b6447c_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.1.0=pyhd3eb1b0_0
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.42.0=ha1441d3_1
  - grpcio=1.42.0=py37hb27c1af_0
  - h5py=3.3.0=nompi_py37ha3df211_100
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2021.8.26=py37h4cda21f_0
  - importlib-metadata=4.11.2=py37h89c1867_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython=7.31.1=py37h06a4308_0
  - jedi=0.18.1=py37h06a4308_1
  - jpeg=9e=h7f98852_0
  - jxrlib=1.1=h7b6447c_2
  - keras=2.7.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.3.2=py37h295c915_0
  - krb5=1.19.2=h3790be6_4
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libcurl=7.81.0=h2574ce0_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_13
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.47.0=h727a467_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.19.4=h780b84a_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_13
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=13.0.1=he0ac6c6_1
  - locket=0.2.1=py37h06a4308_1
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - matplotlib-base=3.5.1=py37ha18d171_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - multidict=6.0.2=py37h5e8e339_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - numpy-base=1.21.2=py37h79a1101_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1m=h7f8727e_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - patchelf=0.14.5=h58526e2_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py37h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.19.4=py37hcd2ae1e_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pysocks=1.7.1=py37h89c1867_4
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.1.1=py37h7b6447c_2
  - pyyaml=6.0=py37h7f8727e_1
  - re2=2021.11.01=h9c3ff4c_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - scikit-image=0.18.3=py37h51133e4_0
  - scipy=1.7.3=py37hc147768_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.37.2=hc218d9a_0
  - tensorboard=2.6.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py37hf1a17b8_1
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.7.0=cpu_py37h08536eb_0
  - tensorflow-base=2.7.0=cpu_py37h8697747_0
  - tensorflow-estimator=2.7.0=cpu_py37h6f16af5_0
  - termcolor=1.1.0=py_2
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py37_cu102
  - torchvision=0.12.0=py37_cu102
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.3=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.13.3=py37h5e8e339_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.0=py37h8f50634_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.4.9=haebb681_0
  - pip:
    - cffi==1.15.0
    - cython==0.29.28
    - fasteners==0.15
    - glfw==1.12.0
    - gym==0.22.0
    - gym-notices==0.0.5
    - imageio==2.16.1
    - monotonic==1.6
    - mujoco-py==2.1.2.14
    - numpy==1.21.5
    - pillow==9.0.1
    - typing-extensions==4.1.1
